export const testPlants = [
  {
    id: 1,
    name: 'Plant1',
    light_min: 100,
    light_max: 150,
    temp_min: 20,
    temp_max: 25,
    humidity_min: 40,
    humidity_max: 45,
    fertilizing: '',
    repotting: '',
    pruning: '',
    common_diseases: '',
    appearance: '',
    blooming_time: '',
    image: '',
    public: false,
  },
  {
    id: 2,
    name: 'Plant2',
    light_min: 100,
    light_max: 150,
    temp_min: 20,
    temp_max: 25,
    humidity_min: 40,
    humidity_max: 45,
    fertilizing: '',
    repotting: '',
    pruning: '',
    common_diseases: '',
    appearance: '',
    blooming_time: '',
    image: '',
    public: false,
  },
];
